spring:
  datasource:
    url: ${DB_URL:jdbc:mariadb://127.0.0.1:3306/demo}
    username: ${DB_USERNAME:dev}
    password: ${DB_PASSWORD:}
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        "[format_sql]": true
        "[use_sql_comments]": true

server:
  port: ${SPRING_PORT:8080}
