server.port=8080
spring.application.name=netix-backend

spring.datasource.url=${JDBC_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

//nastaveni pro desky
edesky.api.key=${EDESKY_API_KEY}
edesky.api.url=https://api.edesky.cz/v1/
edesky.api.url=https://edesky.cz/api/v1/documents

logging.level.org.springframework.web=DEBUG
logging.level.cz.netix.netixbackend=DEBUG