sonar.projectKey=netix-proj
sonar.organization=rsime

sonar.sources=netix-backend/src/main/java,netix-react/src
sonar.exclusions=**/node_modules/**,**/dist/**,**/target/**

# aby Java analyzátor našel compiled classes
sonar.java.binaries=netix-backend/target/classes