server.port=8080
server.address=0.0.0.0

spring.datasource.url=jdbc:mariadb://192.168.3.31:3306/netx
spring.datasource.username=dev
spring.datasource.password=draCo-2025

spring.jpa.hibernate.ddl-auto=update

management.server.port=8081
management.endpoints.web.base-path=/actuator
management.endpoints.web.exposure.include=health,info